version: '3'
services:
  api:
    image: "h404/vehicle-builder"
    ports:
     - "8080:8080"
    environment:
     - DB_HOST=postgres
     - DB_USER=postgres
     - DB_PORT=5432
     - DB_PASS=password
     - DB_NAME=vehicle-builder
  postgres:
    image: "h404/vehicle-builder:db"
