"""Added vehicles table

Revision ID: 9593d51df39f
Revises: 9992cda658ec
Create Date: 2018-10-23 02:08:18.577012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9593d51df39f'
down_revision = '9992cda658ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('range', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles'))
    )
    op.create_table('vehicle_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(length=32), nullable=True),
    sa.Column('value', sa.String(length=32), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_vehicle_properties__vehicle_id__vehicles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_properties'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_properties')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
