"""Add constraints

Revision ID: 9f6b21727930
Revises: e087bae23cef
Create Date: 2018-10-23 12:19:50.068186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6b21727930'
down_revision = 'e087bae23cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_components__sku'), 'components', ['sku'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_components__sku'), 'components', type_='unique')
    # ### end Alembic commands ###
