"""Add vehicle configuration tables

Revision ID: a4b8a6228245
Revises: 7b4d3781b0b0
Create Date: 2018-10-23 10:09:41.324397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b8a6228245'
down_revision = '7b4d3781b0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('fk_vehicle_configurations__feature_id__features'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_vehicle_configurations__vehicle_id__vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_configurations'))
    )
    op.create_table('vehicle_functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], name=op.f('fk_vehicle_functions__function_id__functions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_vehicle_functions__vehicle_id__vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_functions'))
    )
    op.create_table('vehicle_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_function_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('interface_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name=op.f('fk_vehicle_connections__component_id__components'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], name=op.f('fk_vehicle_connections__interface_id__interfaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_function_id'], ['vehicle_functions.id'], name=op.f('fk_vehicle_connections__vehicle_function_id__vehicle_functions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_connections'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_connections')
    op.drop_table('vehicle_functions')
    op.drop_table('vehicle_configurations')
    # ### end Alembic commands ###
